development:
  sessions:
    default:
      database: houseshare_development
      hosts:
        - localhost:17017
test:
  sessions:
    default:
      database: houseshare_test
      hosts:
        - localhost:17017
